### ISSUE TITLE
Program freezing at websockets.connect()

### ISSUE THREAD

**Issue by Hattorius** [Hattorius/Tradingview-ticker#1]
## Expected Behavior
The program should send authorization messages after which it'll receive updates on the tickers

## Current Behavior
Freezes on `websockets.connect()`, continues the program but freezes eventually when the program tries to send a message https://github.com/Hattorius/Tradingview-ticker/blob/ed2131e958f86baf2aa655f25264fee91d9241d9/start.py#L14-L20

## Steps to Reproduce
The following code should give you the same issue:
```py
tick = ticker()
tick.start()
```

**Comment by Hattorius** [comment]
# Update
## Expected Behavior
The program should connect and continue on the rest of the program

## Current Behavior
Freezes on the line below when trying to connect to the websocket. https://github.com/Hattorius/Tradingview-ticker/blob/eac66017abdc82aa25b6ec9ce2840377525f033f/start.py#L17

## Steps to Reproduce
The following code should give you the same issue:
```py
tick = ticker()
tick.start()
```

**Comment by Hattorius** [comment]
For some dark and unknown reasons it actually starts when you open 50 connections:
```py
for i in range(50):
    print(i+1)
    tick = ticker()
    tick.start()
```
_It doesn't work if you don't include the `print(i+1)`_

**Comment by Hattorius** [comment]
Since https://github.com/Hattorius/Tradingview-ticker/commit/be09b070aec8e7b5f8bf1d746849fe014211fffb it'll need 51 connections instead of 50?
```py
for i in range(51):
    print(i+1)
    tick = ticker()
    tick.start()
```

This is spooky man :(

**Comment by Antony1060** [comment]
👻 Computers are spooky

**Comment by GnarLito** [comment]
appears to be an issue with closing the threads before they're fully started, this is only a problem when 1 instance is created.

To fix this issue add a sleep function to the end of the file.
```py
time.sleep(1)
```
This will make sure all threads are fully running before closing the main thread.
