### ISSUE TITLE
can you query indicator?

### ISSUE THREAD

**Issue by xiaopihaiK** [Hattorius/Tradingview-ticker#2]
can you query indicator?

**Comment by xiaopihaiK** [comment]
Can I get real-time indicator data on the page?

**Comment by Hattorius** [comment]
Which indicator data do you mean?

**Comment by xiaopihaiK** [comment]
such ,rsi

**Comment by xiaopihaiK** [comment]
My account is a premium account. I want to get the indicator data in my current chart through websocket in real time. What should I do? Thank you very much for your answer!

**Comment by xiaopihaiK** [comment]
such as "True Strength Indicator (value:7:1:13)"，can you get data，real time，thankyou

**Comment by Hattorius** [comment]
> such as "True Strength Indicator (value:7:1:13)"，can you get data，real time，thankyou

Can you give me a link where I can see an example of this?
