### ISSUE TITLE
Timestamp

### ISSUE THREAD

**Issue by tameike000** [Hattorius/Tradingview-ticker#3]
Hi!
Great work.
Any chance to get a timestamp with .states?

Thanks
M

**Comment by Hattorius** [comment]
Yo! Thanks for the issue @tameike000, took me a while to implement this (cause I haven't worked on this for a while) but it should be available here: https://github.com/Hattorius/Tradingview-ticker/commit/00ff5669556422a7b4f611ecfe61f1e68dfea320, or just pull / download the latest version. Thanks!

**Comment by tameike000** [comment]
@Hattorius You are a rockstar!
Thanks!
