### ISSUE TITLE
Continuous Zero Data Output from TradingView Chart WebSocket

### ISSUE THREAD

**Issue by bigrocks918** [Hattorius/Tradingview-ticker#4]
Hello 

I am currently using your script to receive real-time price data from TradingView chart WebSocket. The script executes without any error messages; however, the data received is continuously zero. I have verified that my WebSocket connection is stable.
I am wondering if there is any other steps to take after following all the steps written in README.md

Thank you
![tvt_err](https://github.com/Hattorius/Tradingview-ticker/assets/119033448/e6006a81-c18f-433a-92b9-d44467e1c25c)

**Comment by Hattorius** [comment]
Fixed, see: https://github.com/Hattorius/Tradingview-ticker/commit/b48e499871aa7731dd2ace9bd372c8f3e1ce644f
